---
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: youapp-backend-test
      MONGO_INITDB_ROOT_PASSWORD: youapp-backend-test
      MONGO_INITDB_DATABASE: youapp-backend-test
    volumes:
      - ./.data/mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint/mongo-init.js:ro
